blank_issues_enabled: false
contact_links:
  - name: "SPSFbaSync Discussions"
    url: https://github.com/luigilink/SPSFbaSync/discussions
    about: "To engage with the community and maintainers of SPSFbaSync, please visit the discussions group. There, you can share feedback, ask questions, and collaborate with others working on SPSFbaSync."
